### ISSUE TITLE
Using a squares chessboard?

### ISSUE THREAD

**Issue by antithing** [Yucao42/g2o_pose_optimization#1]
Hi, and thank you for making this code available. I realise this is an old repo, but it is exactly what I am trying to do (calculate very accurate extrinsics of two different cameras  using pnp with a chessboard, and optimisation).

I use a checkerboard, however, instead of board with dots/circles.

I see in the g2o edge function:

https://github.com/Yucao42/g2o_pose_optimization/blob/59b1c3456a5729fdd8a0dabbc908b27250d329ad/src/Optimizer.cpp#L184

 you have:

```
 e->Xw[0] = (float)( (i%7)* 8);//8mm each with 7 circles a row
 e->Xw[1] = (float)(i%7?row:++row)*8;
 e->Xw[2] = (float)(0);
```

I assume that I need to change this. My checkerboard is:

```
int grid_size_x = 7;
int grid_size_y = 5;
double squareSize = 0.045; //4.5 cm

for (int y = 0; y < grid_size_y; y++)
	{
		for (int x = 0; x < grid_size_x; x++)
		{
			object_points_.push_back(cv::Point3f(x * squareSize, y * squareSize, 0));
		}
	}
```

How would I go about changing your code to use this board?
Aside from the `findCircles` to `findChessboardCorners`, is there anything else that I should need to adjust?

Thanks again!

**Comment by Yucao42** [comment]
Sorry that I just read this issue now. I think modifying the centers' coordinates into corners' coordinates according to your chessboard patterns will do. Have you solved that issue?
